service: pwsneeds
frameworkVersion: "3"
plugins:
  - serverless-dotenv-plugin
  - serverless-offline

provider:
  name: aws
  runtime: nodejs16.x
  memorySize: 128
  region: eu-west-3
  stage: ${opt:stage, 'dev'}
functions:
  getAllUsers:
    handler: src/handlers/users/getAllUsers.handler
    events:
      - httpApi:
          path: /users/get-all-users
          method: get
  findUserById:
    handler: src/handlers/users/getOneUser.handler
    events:
      - httpApi:
          path: /users/find-by-id/{id}
          method: get
  createUser:
    handler: src/handlers/users/createUser.handler
    events:
      - httpApi:
          path: /users/create-user
          method: POST
  updateUser:
    handler: src/handlers/users/updateUser.handler
    events:
      - httpApi:
          path: /users/update-user/{id}
          method: PUT
  deleteUser:
    handler: src/handlers/users/deleteUser.handler
    events:
      - httpApi:
          path: /users/delete-user/{id}
          method: DELETE
