service: pwsneeds
frameworkVersion: "3"
plugins:
  - serverless-dotenv-plugin
  - serverless-offline

provider:
  name: aws
  runtime: nodejs16.x
  memorySize: 128
  region: eu-west-3
  stage: ${opt:stage, 'dev'}

#Functions Apis

functions:
  login:
    handler: src/handlers/auth/login.handler
    events:
      - httpApi:
          path: /auth/login
          method: POST
  signup:
    handler: src/handlers/auth/signup.handler
    events:
      - httpApi:
          path: /auth/signup
          method: POST
  signupProvider:
    handler: src/handlers/auth/signupProvider.handler
    events:
      - httpApi:
          path: /auth/signup-provider
          method: POST
  createUser:
    handler: src/handlers/users/createUser.handler
    events:
      - httpApi:
          path: /users/create-user
          method: POST
  getAllUsers:
    handler: src/handlers/users/getAllUsers.handler
    events:
      - httpApi:
          path: /users/get-all-users
          method: GET
  getCurrentUser:
    handler: src/handlers/users/getCurrentUser.handler
    events:
      - httpApi:
          path: /users/get-current-user
          method: GET
  findUserById:
    handler: src/handlers/users/findUserById.handler
    events:
      - httpApi:
          path: /users/find-user-by-id/{id}
          method: GET
  updateCurrentUser:
    handler: src/handlers/users/updateCurrentUser.handler
    events:
      - httpApi:
          path: /users/update-current-user
          method: PUT
  updateUserById:
    handler: src/handlers/users/updateUserById.handler
    events:
      - httpApi:
          path: /users/update-user/{id}
          method: PUT
  deleteUser:
    handler: src/handlers/users/deleteUser.handler
    events:
      - httpApi:
          path: /users/delete-user/{id}
          method: DELETE

  #Service Categories EndPoints
  createServiceCategory:
    handler: src/handlers/serviceCategory/createServiceCategory.handler
    events:
      - httpApi:
          path: /servicesCategory/create
          method: POST
  getAllServiceCategories:
    handler: src/handlers/serviceCategory/getAllServicesCategory.handler
    events:
      - httpApi:
          path: /servicesCategory/get
          method: GET
  deleteServiceCategory:
    handler: src/handlers/serviceCategory/deleteServiceCategory.handler
    events:
      - httpApi:
          path: /servicesCategory/delete/{id}
          method: DELETE
  updateServiceCategory:
    handler: src/handlers/serviceCategory/updateServiceCategory.handler
    events:
      - httpApi:
          path: /servicesCategory/update/{id}
          method: PUT
  #Services EndPoints
  createService:
    handler: src/handlers/services/createService.handler
    events:
      - httpApi:
          path: /services/create
          method: POST
  getAllServices:
    handler: src/handlers/services/getAllServices.handler
    events:
      - httpApi:
          path: /services/get
          method: GET
  getServiceByCategoryId:
    handler: src/handlers/services/servicesByCategoryId.handler
    events:
      - httpApi:
          path: /services/get-by-category-id/{id}
          method: GET
  updateService:
    handler: src/handlers/services/updateService.handler
    events:
      - httpApi:
          path: /services/update/{id}
          method: PUT
  deleteService:
    handler: src/handlers/services/deleteService.handler
    events:
      - httpApi:
          path: /services/delete/{id}
          method: DELETE
