service: pwsneeds
frameworkVersion: '3'
plugins:
  - serverless-dotenv-plugin
  - serverless-offline

provider:
  name: aws
  runtime: nodejs16.x
  memorySize: 128
  region: eu-west-3
  stage: ${opt:stage, 'dev'}
functions:
  createUser:
    handler: src/handlers/createUser.handler
    events:
      - httpApi:
          path: /users
          method: POST
  getUsers:
    handler: src/handlers/users.getAll
    events:
      - httpApi:
          path: /users/get
          method: get
  findUserByEmail:
    handler: src/handlers/users.getByEmail
    events:
      - httpApi:
          path: /users/{email}
          method: get
